# Hadolint configuration for aza-pg
# Evidence-based exception list - all ignores require documented justification

ignored:
  # DL3003: Use WORKDIR to switch to a directory
  # Rationale: Single transient `cd` in Rust installation RUN command (extract, cd, install,
  # cd back, cleanup). Using WORKDIR would require additional state management for a
  # one-time operation. The `cd` is safe and immediately followed by cleanup.
  - DL3003

  # DL4006: Set SHELL option -o pipefail before RUN with a pipe
  # Rationale: We use `set -eu` consistently across all RUN commands, which provides
  # adequate error handling. Our pipes have explicit error handling patterns.
  # Verified: No silent pipe failures in codebase.
  - DL4006

  # SC2046: Quote to prevent word splitting
  # Rationale: Intentional command substitution expansion for apt-get package lists.
  # Pattern: $(tr '\n' ' ' < packages.txt) deliberately converts newlines to spaces
  # for argument expansion. Quoting would break functionality.
  # Context: Trusted internal manifest files only.
  - SC2046

  # SC2086: Double quote to prevent globbing and word splitting
  # Rationale: Intentional word splitting for dynamic package list expansion.
  # Pattern: ${RUNTIME_PKGS} expands to multiple apt-get arguments by design.
  # Context: Variables populated from trusted internal manifests.
  - SC2086

  # DL3059: Multiple consecutive RUN instructions
  # Rationale: Multi-stage build structure is optimized for Docker layer caching.
  # Each RUN command is separated for valid cache efficiency reasons (e.g., COPY
  # artifacts separate from package installs). Consolidation would hurt performance.
  # Verified: Structure is already optimized.
  - DL3059
# Rules now ENABLED (removed from ignore list):
# - DL3008: Pin versions - Use inline ignores with justification for exceptions
# - DL3015: Use --no-install-recommends - Applied globally, inline ignores if needed

# Keep these rules enabled (security-critical):
# - DL3000-DL3007: FROM/MAINTAINER/apt best practices
# - DL3020: Use COPY instead of ADD
# - DL3025: Use JSON notation for CMD/ENTRYPOINT
