-- Generated by: bun scripts/pgflow/generate-schema.ts (do not edit)
-- Source: 0010_extensions.sql
-- Extensions must be created first
CREATE EXTENSION if NOT EXISTS pgmq;


-- Extensions for worker management
-- pg_net: HTTP requests from SQL (for pinging edge functions)
CREATE EXTENSION if NOT EXISTS pg_net;


-- supabase_vault: Secure credential storage (service role key, base URL)
-- supabase_vault: created below only where available (aza-pg)
-- pg_cron: Scheduled job execution (ensure_workers cron)
DO $extensions$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'supabase_vault') THEN
    CREATE EXTENSION IF NOT EXISTS supabase_vault;
  END IF;
  IF current_database() = current_setting('cron.database_name', true) THEN
    CREATE EXTENSION IF NOT EXISTS pg_cron;
  END IF;
END
$extensions$;


-- Source: 0030_utilities.sql
-- Utility functions that don't depend on other entities
-- Detects if running in local Supabase CLI environment
-- by checking if JWT secret matches the known hardcoded local value.
-- Returns true only for exact match; defaults to false (production-safe).
CREATE OR REPLACE FUNCTION pgflow.is_local () returns BOOLEAN language sql stable parallel safe
SET
  search_path = '' AS $$
  select coalesce(
    current_setting('app.settings.jwt_secret', true)
      = 'super-secret-jwt-token-with-at-least-32-characters-long',
    false
  )
$$;


CREATE OR REPLACE FUNCTION pgflow.is_valid_slug (slug TEXT) returns BOOLEAN language plpgsql immutable
SET
  search_path = '' AS $$
begin
    return
      slug is not null
      and slug <> ''
      and length(slug) <= 128
      and slug ~ '^[a-zA-Z_][a-zA-Z0-9_]*$'
      and slug NOT IN ('run') -- reserved words
      -- #651: '__' is reserved for pgflow-generated queue names and
      -- boundary underscores are rejected for flows and steps alike
      and left(slug, 1) ~ '[a-zA-Z]'
      and right(slug, 1) ~ '[a-zA-Z0-9]'
      and position('__' in slug) = 0;
end;
$$;


CREATE OR REPLACE FUNCTION pgflow.is_valid_queue_name (queue_name TEXT) returns BOOLEAN language sql immutable
SET
  search_path = '' AS $$
  -- Mirrors pgmq.validate_queue_name() (47-character limit) and additionally
  -- requires the canonical lowercase spelling pgflow stores (#650).
  select
    queue_name is not null
    and queue_name <> ''
    and length(queue_name) <= 47
    and queue_name = lower(queue_name)
$$;


CREATE OR REPLACE FUNCTION pgflow.calculate_retry_delay (base_delay NUMERIC, attempts_count INT) returns INT language sql immutable parallel safe
SET
  search_path = '' AS $$
  select floor(base_delay * power(2, attempts_count))::int
$$;


-- Source: 0059_function_ensure_workers.sql
-- AZA PostgreSQL Vault Secret Compatibility
-- Reads Supabase Vault secrets without binding pgflow schema installation to vault.decrypted_secrets.
CREATE OR REPLACE FUNCTION pgflow.aza_vault_secret (secret_name TEXT) returns TEXT language plpgsql stable
SET
  search_path = '' AS $$
DECLARE
  secret_value TEXT;
BEGIN
  IF to_regclass('vault.decrypted_secrets') IS NULL THEN
    RETURN NULL;
  END IF;

  EXECUTE $query$
    SELECT nullif(decrypted_secret, '')
    FROM vault.decrypted_secrets
    WHERE name = $1
    LIMIT 1
  $query$
  INTO secret_value
  USING secret_name;

  RETURN secret_value;
END;
$$;


COMMENT ON function pgflow.aza_vault_secret (TEXT) IS 'Reads a Supabase Vault secret when vault.decrypted_secrets exists; returns NULL when Vault is not installed in this database.';


-- Ensure Workers
-- Returns which worker functions should be invoked, makes HTTP requests, and updates last_invoked_at
-- Called by cron job to keep workers running
CREATE OR REPLACE FUNCTION pgflow.ensure_workers () returns TABLE (function_name TEXT, invoked BOOLEAN, request_id BIGINT) language sql AS $$
  with
    -- Detect environment
    env as (
      select pgflow.is_local() as is_local
    ),

    -- Get credentials: Local mode uses hardcoded URL, production uses vault secrets
    -- Empty strings are treated as NULL using nullif()
    -- pgflow_auth_secret takes priority over supabase_service_role_key for production auth
    credentials as (
      select
        case
          when (select is_local from env) then null
          else coalesce(
            pgflow.aza_vault_secret('pgflow_auth_secret'),
            pgflow.aza_vault_secret('supabase_service_role_key')
          )
        end as service_role_key,
        case
          when (select is_local from env) then 'http://kong:8000/functions/v1'
          else 'https://' || pgflow.aza_vault_secret('supabase_project_id') || '.supabase.co/functions/v1'
        end as base_url
    ),

    -- Only HTTP-started worker functions are supervised via HTTP pings.
    http_worker_functions as (
      select wf.function_name, wf.debounce, wf.last_invoked_at
      from pgflow.worker_functions as wf
      where wf.enabled = true
        and wf.start_mode = 'http'
    ),

    -- Find functions that pass the debounce check
    debounce_passed as (
      select wf.function_name, wf.debounce
      from http_worker_functions as wf
      where wf.last_invoked_at is null
        or wf.last_invoked_at < now() - wf.debounce
    ),

    -- Find functions that have at least one alive worker
    functions_with_alive_workers as (
      select distinct w.function_name
      from pgflow.workers as w
      inner join debounce_passed as dp on w.function_name = dp.function_name
      where w.stopped_at is null
        and w.deprecated_at is null
        and w.last_heartbeat_at > now() - dp.debounce
    ),

    -- Determine which functions should be invoked
    -- Local mode: all enabled functions (bypass debounce AND alive workers check)
    -- Production mode: only functions that pass debounce AND have no alive workers
    functions_to_invoke as (
      select wf.function_name
      from http_worker_functions as wf
      where pgflow.is_local() = true  -- Local: all enabled HTTP functions
        or (
          -- Production: debounce + no alive workers
          wf.function_name in (select dp.function_name from debounce_passed as dp)
          and wf.function_name not in (select faw.function_name from functions_with_alive_workers as faw)
        )
    ),

    -- Make HTTP requests and capture request_ids
    http_requests as (
      select
        fti.function_name,
        net.http_post(
          url => c.base_url || '/' || fti.function_name,
          headers => case
            when e.is_local then '{}'::jsonb
            else jsonb_build_object(
              'Content-Type', 'application/json',
              'Authorization', 'Bearer ' || c.service_role_key
            )
          end,
          body => '{}'::jsonb
        ) as request_id
      from functions_to_invoke as fti
      cross join credentials as c
      cross join env as e
      where c.base_url is not null
        and (e.is_local or c.service_role_key is not null)
    ),

    -- Update last_invoked_at for invoked functions
    updated as (
      update pgflow.worker_functions as wf
      set last_invoked_at = clock_timestamp()
      from http_requests as hr
      where wf.function_name = hr.function_name
      returning wf.function_name
    )

  select u.function_name, true as invoked, hr.request_id
  from updated as u
  inner join http_requests as hr on u.function_name = hr.function_name
$$;


COMMENT ON function pgflow.ensure_workers () IS 'Ensures worker functions are running by pinging them via HTTP when needed.
In local mode: pings ALL enabled functions (ignores debounce AND alive workers check).
In production mode: only pings functions that pass debounce AND have no alive workers.
Debounce: skips functions pinged within their debounce interval (production only).
Credentials: Uses Vault secrets (pgflow_auth_secret with fallback to supabase_service_role_key, supabase_project_id) or local fallbacks.
URL is built from project_id: https://{project_id}.supabase.co/functions/v1
Returns request_id from pg_net for each HTTP request made.';


-- Source: 0060_function_cleanup_ensure_workers_logs.sql
-- Cleanup Ensure Workers Logs
-- Cleans up old cron job run details to prevent the table from growing indefinitely.
-- Note: net._http_response is automatically cleaned by pg_net (6 hour TTL), so we only clean cron logs.
CREATE OR REPLACE FUNCTION pgflow.cleanup_ensure_workers_logs (retention_hours INTEGER DEFAULT 24) returns TABLE (cron_deleted BIGINT) language plpgsql security definer
SET
  search_path = pgflow,
  pg_temp AS $$
DECLARE
  deleted_count BIGINT;
BEGIN
  IF to_regclass('cron.job_run_details') IS NULL THEN
    RETURN QUERY SELECT 0::BIGINT;
    RETURN;
  END IF;

  EXECUTE 'DELETE FROM cron.job_run_details WHERE end_time < now() - make_interval(hours => $1)'
  USING retention_hours;
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN QUERY SELECT deleted_count;
END;
$$;


COMMENT ON function pgflow.cleanup_ensure_workers_logs (INTEGER) IS 'Cleans up old cron job run details to prevent table growth.
Default retention is 24 hours. HTTP response logs (net._http_response) are
automatically cleaned by pg_net with a 6-hour TTL, so they are not cleaned here.
Returns 0 when pg_cron is configured in another database and cron.job_run_details
is absent from the current database.
This function follows the standard pg_cron maintenance pattern recommended by
AWS RDS, Neon, and Supabase documentation.';


-- Source: 0061_function_setup_ensure_workers_cron.sql
-- Setup Ensure Workers Cron
-- Sets up cron jobs for worker management: ensure_workers (configurable interval) and cleanup_logs (hourly)
CREATE OR REPLACE FUNCTION pgflow.setup_ensure_workers_cron (cron_interval TEXT DEFAULT '1 second') returns TEXT language plpgsql security definer
SET
  search_path = pgflow,
  pg_temp AS $$
declare
  ensure_workers_job_id bigint;
  cleanup_job_id bigint;
begin
  IF to_regprocedure('cron.schedule(text,text,text)') IS NULL THEN
    RETURN 'pg_cron is not available in this database; skipped pgflow worker cron setup';
  END IF;

  -- Remove existing jobs if they exist (ignore errors if not found)
  begin
    perform cron.unschedule('pgflow_ensure_workers');
  exception when others then
    -- Job doesn't exist, continue
  end;

  begin
    perform cron.unschedule('pgflow_cleanup_logs');
  exception when others then
    -- Job doesn't exist, continue
  end;

  -- Schedule ensure_workers job with the specified interval
  ensure_workers_job_id := cron.schedule(
    job_name => 'pgflow_ensure_workers',
    schedule => setup_ensure_workers_cron.cron_interval,
    command => 'select pgflow.ensure_workers()'
  );

  -- Schedule cleanup job to run hourly
  cleanup_job_id := cron.schedule(
    job_name => 'pgflow_cleanup_logs',
    schedule => '0 * * * *',
    command => 'select pgflow.cleanup_ensure_workers_logs()'
  );

  return format(
    'Scheduled pgflow_ensure_workers (every %s, job_id=%s) and pgflow_cleanup_logs (hourly, job_id=%s)',
    setup_ensure_workers_cron.cron_interval,
    ensure_workers_job_id,
    cleanup_job_id
  );
end;
$$;


COMMENT ON function pgflow.setup_ensure_workers_cron (TEXT) IS 'Sets up cron jobs for worker management.
Schedules pgflow_ensure_workers at the specified cron_interval (default: 1 second) to keep workers running.
Schedules pgflow_cleanup_logs hourly to clean up old cron job logs.
Replaces existing jobs if they exist (idempotent).
Returns a skipped message when pg_cron is configured in another database.
Returns a confirmation message with job IDs.';


-- Source: 0063_function_setup_requeue_stalled_tasks_cron.sql
-- Cron setup function for automatic requeue monitoring
CREATE OR REPLACE FUNCTION pgflow.setup_requeue_stalled_tasks_cron (cron_interval TEXT DEFAULT '15 seconds') returns TEXT language plpgsql security definer
SET
  search_path = pgflow,
  pg_temp AS $$
declare
  job_id bigint;
begin
  IF to_regprocedure('cron.schedule(text,text,text)') IS NULL THEN
    RETURN 'pg_cron is not available in this database; skipped pgflow stalled-task cron setup';
  END IF;

  -- Remove existing job if any
  begin
    perform cron.unschedule('pgflow_requeue_stalled_tasks');
  exception
    when others then null;
  end;

  -- Schedule the new job
  job_id := cron.schedule(
    job_name => 'pgflow_requeue_stalled_tasks',
    schedule => setup_requeue_stalled_tasks_cron.cron_interval,
    command => 'select pgflow.requeue_stalled_tasks()'
  );

  return format('Scheduled pgflow_requeue_stalled_tasks (every %s, job_id=%s)',
    setup_requeue_stalled_tasks_cron.cron_interval, job_id);
end;
$$;


COMMENT ON function pgflow.setup_requeue_stalled_tasks_cron (TEXT) IS 'Sets up cron job to automatically requeue stalled tasks.
Schedules pgflow_requeue_stalled_tasks at the specified cron_interval (default: 15 seconds).
Replaces existing job if it exists (idempotent).
Returns a skipped message when pg_cron is configured in another database.
Returns a confirmation message with job ID.';


-- Automatically set up the cron job when migration runs
SELECT
  pgflow.setup_requeue_stalled_tasks_cron ();