-- PostgreSQL initialization: enable baseline extensions
-- Runs automatically on first cluster start.
-- Generated by scripts/config-generator/generator.ts from extensions.manifest.json
--
-- DO NOT EDIT MANUALLY - Changes will be overwritten
-- Edit docker/postgres/extensions.manifest.json and regenerate

-- Core extensions pre-enabled by default.
-- Note: plpgsql is builtin and always available, no CREATE EXTENSION needed
CREATE EXTENSION IF NOT EXISTS auto_explain; -- auto_explain (observability)
CREATE EXTENSION IF NOT EXISTS pg_cron; -- pg_cron (operations)
CREATE EXTENSION IF NOT EXISTS pg_stat_statements; -- pg_stat_statements (observability)
CREATE EXTENSION IF NOT EXISTS pg_trgm; -- pg_trgm (search)
CREATE EXTENSION IF NOT EXISTS pgaudit; -- pgaudit (security)
CREATE EXTENSION IF NOT EXISTS vector; -- pgvector (ai)

DO $$
BEGIN
  RAISE NOTICE 'Baseline extensions enabled (auto_explain, pg_cron, pg_stat_statements, pg_trgm, pgaudit, vector). Additional extensions are available but disabled by default. plpgsql is builtin and always available.';
END;
$$;
