name: Load Test Image
description: Load Docker image from artifact or registry

inputs:
  source:
    description: Image source (artifact or registry)
    required: true
  image-name:
    description: Docker image name/tag to use
    required: true
  artifact-name:
    description: Artifact name (required if source=artifact)
    required: false
    default: docker-image
  artifact-path:
    description: Artifact download path (required if source=artifact)
    required: false
    default: /tmp
  registry-image:
    description: Full registry image reference (required if source=registry)
    required: false
  max-retries:
    description: "Max retries for registry pull (default: 3)"
    required: false
    default: "3"

runs:
  using: composite
  steps:
    - name: Download image artifact
      if: inputs.source == 'artifact'
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    - name: Load Docker image from artifact
      if: inputs.source == 'artifact'
      shell: bash
      run: |
        set -euo pipefail
        echo "Loading Docker image from artifact..."

        # Parse docker load output to get exact loaded image reference (deterministic)
        # Avoids race condition from grepping image list when multiple matches exist
        LOAD_OUTPUT=$(docker load < ${{ inputs.artifact-path }}/aza-pg-ci-image.tar.gz)
        LOADED_IMAGE=$(echo "$LOAD_OUTPUT" | grep -oP 'Loaded image: \K.*' | head -1)

        if [ -z "$LOADED_IMAGE" ]; then
          echo "❌ ERROR: Failed to extract loaded image reference from output"
          echo "Docker load output: $LOAD_OUTPUT"
          exit 1
        fi

        echo "Loaded image: $LOADED_IMAGE"

        # Tag with requested name if different from loaded image
        if [ "$LOADED_IMAGE" != "${{ inputs.image-name }}" ]; then
          docker tag "$LOADED_IMAGE" "${{ inputs.image-name }}"
          echo "Tagged $LOADED_IMAGE as ${{ inputs.image-name }}"
        fi

        docker images | grep aza-pg-ci || docker images
        echo "✅ Image loaded successfully"

    - name: Set up Bun and dependencies (for registry pull)
      if: inputs.source == 'registry'
      uses: ./.github/actions/setup-bun

    - name: Pull image from registry
      if: inputs.source == 'registry'
      shell: bash
      run: |
        set -euo pipefail
        echo "Pulling Docker image from registry..."
        bun scripts/docker/pull-with-retry.ts \
          --image "${{ inputs.registry-image }}" \
          --max-retries ${{ inputs.max-retries }}

        # Tag with local name for consistency
        docker tag "${{ inputs.registry-image }}" "${{ inputs.image-name }}"
        echo "✅ Image pulled and tagged: ${{ inputs.image-name }}"
