#!/usr/bin/env bun

import { join } from "node:path";
import type { StackType, PostgreSQLSettings } from "./types";
import { BASE_CONFIG, LOCAL_PEER_MAP } from "./base-config";
import { formatSetting } from "../utils/guc-formatter";
import {
  loadManifest,
  getDefaultEnabledExtensions,
  getDefaultSharedPreloadLibraries,
} from "./manifest-loader";
import { generateExtensionsInitScript } from "./sql-generator";
import { generateHealthcheckScript } from "./healthcheck-generator";
import { writeConfigFile, writeConfigWithDir } from "./config-writer";
import { success, info, error } from "../utils/logger";

const SHARED_CATEGORY_FIELDS = {
  io: ["ioMethod", "ioCombineLimit"] as const,
  pg_stat_statements: ["pgStatStatementsMax", "pgStatStatementsTrack"] as const,
  autovacuum: [
    "autovacuum",
    "autovacuumNaptime",
    "autovacuumVacuumCostDelay",
    "autovacuumVacuumCostLimit",
    "autovacuumVacuumScaleFactor",
    "autovacuumAnalyzeScaleFactor",
    "autovacuumFreezeMaxAge",
  ] as const,
};

const REPO_ROOT = join(import.meta.dir, "../..");

// The entrypoint's tuned values outrank this file (docs/ARCHITECTURE.md "Configuration Hierarchy"), so a tuned setting
// written here would never apply and would be logged as ignored on every start; validate-configs rejects one.
const AUTO_TUNED_NOTE = [
  "# Auto-tuned settings (memory, connections, workers, WAL sizes, wal_level, listen_addresses,",
  "# shared_preload_libraries, ...) are not set here: the entrypoint's values outrank this file.",
  "# Override one with ALTER SYSTEM or -c name=value.",
].join("\n");

function mergeSettings(
  common: PostgreSQLSettings,
  stackOverrides: Partial<PostgreSQLSettings>
): PostgreSQLSettings {
  return { ...common, ...stackOverrides };
}

function generatePostgresqlConf(
  stack: StackType,
  settings: PostgreSQLSettings,
  overrides: Partial<PostgreSQLSettings>,
  defaultPreloads: string
): string {
  const lines: string[] = [];

  lines.push("# PostgreSQL Configuration");
  lines.push(`# Stack: ${stack}`);
  lines.push("# Generated by scripts/config-generator/generator.ts");
  lines.push("#");
  lines.push("# DO NOT EDIT MANUALLY - Changes will be overwritten");
  lines.push("# Edit scripts/config-generator/base-config.ts and regenerate");
  lines.push(
    "# The image's entrypoint includes /etc/postgresql/postgresql-base.conf before this file."
  );
  lines.push("");

  const categories = {
    connection: ["port", "sharedPreloadLibraries", "idleSessionTimeout"],
    io: [...SHARED_CATEGORY_FIELDS.io],
    logging: [
      "logDestination",
      "loggingCollector",
      "logMinDurationStatement",
      "logLinePrefix",
      "logLockWaits",
      "logTempFiles",
      "logTimezone",
      "logCheckpoints",
      "logConnections",
      "logDisconnections",
      "logAutovacuumMinDuration",
      "logReplicationCommands",
    ],
    locale: [
      "timezone",
      "lcMessages",
      "lcMonetary",
      "lcNumeric",
      "lcTime",
      "defaultTextSearchConfig",
    ],
    pg_stat_statements: [...SHARED_CATEGORY_FIELDS.pg_stat_statements],
    auto_explain: [
      "autoExplainLogMinDuration",
      "autoExplainLogAnalyze",
      "autoExplainLogBuffers",
      "autoExplainLogNestedStatements",
      "autoExplainLogTiming",
    ],
    autovacuum: [...SHARED_CATEGORY_FIELDS.autovacuum],
    wal: ["walCompression", "maxWalSenders", "walKeepSize", "archiveMode", "archiveCommand"],
    replication: [
      "synchronousCommit",
      "synchronousStandbyNames",
      "maxReplicationSlots",
      "idleReplicationSlotTimeout",
      "walSenderTimeout",
      "hotStandby",
      "maxStandbyArchiveDelay",
      "maxStandbyStreamingDelay",
      "hotStandbyFeedback",
      "walReceiverStatusInterval",
      "logReplicationCommands",
    ],
    pg_cron: ["cronLogRun", "cronLogStatement"],
    pgaudit: ["pgAuditLog", "pgAuditLogStatementOnce", "pgAuditLogLevel", "pgAuditLogRelation"],
  };

  const includeCategories: Record<StackType, string[]> = {
    single: ["wal", "pgaudit"],
    primary: ["replication", "wal", "pg_cron", "pgaudit"],
    replica: ["replication", "wal", "pg_cron", "pgaudit"],
  };

  for (const cat of includeCategories[stack]) {
    const categoryKeys = categories[cat as keyof typeof categories];
    const categoryLines: string[] = [];

    for (const key of categoryKeys) {
      if (overrides[key as keyof PostgreSQLSettings] === undefined) {
        continue;
      }

      const value = settings[key as keyof PostgreSQLSettings];
      if (value !== undefined) {
        const formatted = formatSetting(key, value);
        if (formatted) {
          categoryLines.push(formatted);
        }
      }
    }

    if (categoryLines.length > 0) {
      lines.push(`# ${cat.replace(/_/g, " ").toUpperCase()}`);
      lines.push(...categoryLines);
      lines.push("");
    }
  }

  if (stack === "replica" || stack === "single") {
    if (overrides.autoExplainLogTiming !== undefined) {
      lines.push("# AUTO EXPLAIN");
      lines.push(formatSetting("autoExplainLogTiming", settings.autoExplainLogTiming));
      lines.push("");
    }
  }

  if (
    stack === "primary" &&
    overrides.archiveMode !== undefined &&
    settings.archiveMode === "off"
  ) {
    lines.push("# WAL Archiving (disabled by default)");
    lines.push("# Uncomment and configure for Point-in-Time Recovery (PITR):");
    lines.push("# archive_mode = 'on'");
    lines.push("# archive_command = 'cp %p /backup/wal/%f'");
    lines.push("");
  }

  lines.push(AUTO_TUNED_NOTE);
  lines.push(`# Default shared_preload_libraries: ${defaultPreloads}`);

  return lines.join("\n");
}

function generateBaseConf(settings: PostgreSQLSettings): string {
  const lines: string[] = [];

  lines.push("# PostgreSQL 18 Base Configuration");
  lines.push("# ============================================");
  lines.push("# Shared settings across all aza-pg deployments (primary, replica, single).");
  lines.push("# Generated by scripts/config-generator/generator.ts");
  lines.push("#");
  lines.push("# DO NOT EDIT MANUALLY - Changes will be overwritten");
  lines.push("# Edit scripts/config-generator/base-config.ts and regenerate");
  lines.push("#");
  lines.push(AUTO_TUNED_NOTE);
  lines.push("");

  const categories = {
    connection: ["sharedPreloadLibraries"],
    io: [...SHARED_CATEGORY_FIELDS.io],
    logging: [
      "logDestination",
      "loggingCollector",
      "logMinDurationStatement",
      "logLinePrefix",
      "logLockWaits",
      "logTempFiles",
      "logCheckpoints",
      "logConnections",
      "logDisconnections",
      "logAutovacuumMinDuration",
    ],
    locale: [
      "timezone",
      "logTimezone",
      "lcMessages",
      "lcMonetary",
      "lcNumeric",
      "lcTime",
      "defaultTextSearchConfig",
      "clientEncoding",
    ],
    pg_stat_statements: [...SHARED_CATEGORY_FIELDS.pg_stat_statements],
    auto_explain: [
      "autoExplainLogMinDuration",
      "autoExplainLogAnalyze",
      "autoExplainLogBuffers",
      "autoExplainLogNestedStatements",
    ],
    autovacuum: [...SHARED_CATEGORY_FIELDS.autovacuum],
    wal: ["walCompression"],
    timescaledb: ["timescaledbTelemetryLevel"],
    pg_cron: ["cronHost"],
  };

  for (const [catName, categoryKeys] of Object.entries(categories)) {
    const categoryLines: string[] = [];

    for (const key of categoryKeys) {
      const value = settings[key as keyof PostgreSQLSettings];
      if (value !== undefined) {
        const formatted = formatSetting(key, value);
        if (formatted) {
          categoryLines.push(formatted);
        }
      }
    }

    if (categoryLines.length > 0) {
      lines.push(`# ${catName.replace(/_/g, " ").toUpperCase()}`);
      lines.push(...categoryLines);
      lines.push("");
    }
  }

  return lines.join("\n");
}

function generatePgHba(stack: StackType): string {
  const lines: string[] = [];

  lines.push("# PostgreSQL Client Authentication Configuration");
  lines.push(`# Stack: ${stack}`);
  lines.push("# Generated by scripts/config-generator/generator.ts");
  lines.push("#");
  lines.push("# DO NOT EDIT MANUALLY - Changes will be overwritten");
  lines.push("# Edit scripts/config-generator/base-config.ts and regenerate");
  lines.push("");
  lines.push("# TYPE  DATABASE        USER            ADDRESS                 METHOD");
  lines.push("");

  for (const rule of BASE_CONFIG.pgHbaRules) {
    if (rule.stackSpecific && !rule.stackSpecific.includes(stack)) {
      continue;
    }

    if (rule.comment) {
      lines.push(`# ${rule.comment}`);
    }

    const parts = [rule.type, rule.database, rule.user];

    if (rule.address) {
      parts.push(rule.address.padEnd(24));
    }

    parts.push(rule.method);
    if (rule.map) parts.push(`map=${rule.map}`);

    lines.push(parts.join("\t"));
  }

  return lines.join("\n");
}

/** The map the local peer rule consults; `all` (PostgreSQL 16+) lets OS user postgres log in as any role. */
function generatePgIdent(): string {
  return [
    "# Generated by scripts/config-generator/generator.ts - DO NOT EDIT MANUALLY",
    "",
    "# MAPNAME       SYSTEM-USERNAME PG-USERNAME",
    `${LOCAL_PEER_MAP}\tpostgres\tall`,
    "",
  ].join("\n");
}

async function generateConfigs() {
  info("Generating PostgreSQL configurations...\n");

  try {
    // Load manifest first (needed for preload libraries in config comments)
    const manifest = await loadManifest(REPO_ROOT);
    const defaultPreloads = getDefaultSharedPreloadLibraries(manifest);

    // Generate base config
    info("Generating base configuration...");
    const baseConf = generateBaseConf(BASE_CONFIG.common);
    const baseConfPath = join(REPO_ROOT, "docker/postgres/configs/postgresql-base.conf");

    await writeConfigFile(baseConfPath, baseConf);
    console.log(`   ✓ ${baseConfPath}`);

    // Generate stack-specific configs
    const stacks: StackType[] = ["primary", "replica", "single"];

    for (const stack of stacks) {
      info(`Generating ${stack} stack configurations...`);

      const stackOverrides = BASE_CONFIG.stacks[stack];
      const settings = mergeSettings(BASE_CONFIG.common, stackOverrides);
      const postgresqlConf = generatePostgresqlConf(
        stack,
        settings,
        stackOverrides,
        defaultPreloads
      );

      let confDir: string;
      let confName: string;

      if (stack === "single") {
        confDir = join(REPO_ROOT, "stacks/single/configs");
        confName = "postgresql.conf";
      } else {
        confDir = join(REPO_ROOT, `stacks/${stack}/configs`);
        confName = `postgresql-${stack}.conf`;
      }

      const postgresqlConfPath = await writeConfigWithDir(confDir, confName, postgresqlConf);
      console.log(`   ✓ ${postgresqlConfPath}`);

      const pgHbaConf = generatePgHba(stack);
      const pgHbaPath = await writeConfigWithDir(confDir, "pg_hba.conf", pgHbaConf);
      console.log(`   ✓ ${pgHbaPath}`);

      const pgIdentPath = await writeConfigWithDir(confDir, "pg_ident.conf", generatePgIdent());
      console.log(`   ✓ ${pgIdentPath}`);
    }

    // Generate 01-extensions.sql init script
    info("Generating extension init script...");
    const extensionsToEnable = getDefaultEnabledExtensions(manifest);
    const extensionsInitScript = await generateExtensionsInitScript(extensionsToEnable);
    const extensionsInitPath = join(
      REPO_ROOT,
      "docker/postgres/docker-entrypoint-initdb.d/01-extensions.sql"
    );
    await writeConfigFile(extensionsInitPath, extensionsInitScript);
    console.log(`   ✓ ${extensionsInitPath}`);

    // Generate healthcheck.sh script (synchronized with init script)
    info("Generating healthcheck script...");
    const healthcheckScript = generateHealthcheckScript(extensionsToEnable);
    const healthcheckPath = join(REPO_ROOT, "docker/postgres/healthcheck.sh");
    await writeConfigFile(healthcheckPath, healthcheckScript);
    // Make healthcheck executable
    await Bun.write(healthcheckPath, healthcheckScript, { mode: 0o755 });
    console.log(`   ✓ ${healthcheckPath}`);
  } catch (err) {
    const err_error = err as Error;
    error(`Configuration generation failed: ${err_error.message}`);
    process.exit(1);
  }

  success("Configuration generation complete!\n");
  info("Generated files:");
  console.log("   - docker/postgres/configs/postgresql-base.conf");
  console.log("   - stacks/primary/configs/postgresql-primary.conf");
  console.log("   - stacks/primary/configs/pg_hba.conf");
  console.log("   - stacks/primary/configs/pg_ident.conf");
  console.log("   - stacks/replica/configs/postgresql-replica.conf");
  console.log("   - stacks/replica/configs/pg_hba.conf");
  console.log("   - stacks/replica/configs/pg_ident.conf");
  console.log("   - stacks/single/configs/postgresql.conf");
  console.log("   - stacks/single/configs/pg_hba.conf");
  console.log("   - stacks/single/configs/pg_ident.conf");
  console.log("   - docker/postgres/docker-entrypoint-initdb.d/01-extensions.sql");
  console.log("   - docker/postgres/healthcheck.sh");
  console.log("");
}

generateConfigs();
