/**
 * SQL Generator
 * Generates PostgreSQL initialization SQL scripts from manifest data
 */

import type { ManifestEntry } from "../extensions/manifest-data.js";

/**
 * Generate 01-extensions.sql initialization script
 * Creates SQL that enables baseline extensions on first cluster start
 * @param extensionsToEnable - Array of manifest entries for extensions to enable
 * @returns SQL script content as string
 */
export function generateExtensionsInitScript(extensionsToEnable: ManifestEntry[]): string {
  const lines: string[] = [];

  lines.push("-- PostgreSQL initialization: enable baseline extensions");
  lines.push("-- Runs automatically on first cluster start.");
  lines.push("-- Generated by scripts/config-generator/generator.ts from extensions.manifest.json");
  lines.push("--");
  lines.push("-- DO NOT EDIT MANUALLY - Changes will be overwritten");
  lines.push("-- Edit docker/postgres/extensions.manifest.json and regenerate");
  lines.push("");

  if (extensionsToEnable.length > 0) {
    lines.push("-- Core extensions pre-enabled by default.");
    for (const entry of extensionsToEnable) {
      const displayName = entry.displayName ?? entry.name;
      const category = entry.category ?? "misc";
      lines.push(`CREATE EXTENSION IF NOT EXISTS ${entry.name}; -- ${displayName} (${category})`);
    }
  } else {
    lines.push("-- No extensions enabled by default.");
    lines.push(
      "-- All extensions are available but must be created manually via CREATE EXTENSION."
    );
  }

  lines.push("");
  lines.push("DO $$");
  lines.push("BEGIN");

  const extensionNames = extensionsToEnable.map((e) => e.name).join(", ");
  if (extensionNames) {
    lines.push(
      `  RAISE NOTICE 'Baseline extensions enabled (${extensionNames}). Additional extensions are available but disabled by default.';`
    );
  } else {
    lines.push(
      `  RAISE NOTICE 'No baseline extensions enabled. All extensions available but must be created manually.';`
    );
  }

  lines.push("END;");
  lines.push("$$;");
  lines.push("");

  return lines.join("\n");
}
