name: "Login to GitHub Container Registry"
description: "Authenticate with GHCR (ghcr.io) for pushing/pulling images"
author: "fluxo-kt"

inputs:
  token:
    description: "GitHub token for authentication"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
