services:
  postgres:
    image: ${POSTGRES_IMAGE:-aza-pg:pg18-dev}

    mem_limit: ${POSTGRES_DEV_MEMORY_LIMIT:-2000m}
    mem_reservation: ${POSTGRES_DEV_MEMORY_RESERVATION:-512m}

    ports:
      - "5433:5432"

  pgbouncer:
    ports:
      - "6433:6432"

  postgres_exporter:
    ports:
      - "9188:9187"

networks:
  postgres_net:
    name: postgres-replication
    driver: bridge
    attachable: true
