name: "Setup Docker Buildx"
description: "Set up Docker Buildx with network=host driver configuration"
author: "fluxo-kt"

inputs:
  builder-name:
    description: "Name for the buildx builder instance"
    required: false
    default: "multiarch-builder"

outputs:
  builder-name:
    description: "The name of the created builder"
    value: ${{ steps.buildx.outputs.name }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
        buildkitd-flags: --allow-insecure-entitlement network.host
